/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type ExternalBlob = Uint8Array;
export interface Message {
  'to' : UserId,
  'content' : string,
  'from' : UserId,
  'timestamp' : Time,
}
export interface Profile {
  'age' : bigint,
  'bio' : string,
  'displayName' : string,
  'interests' : Array<string>,
  'city' : string,
  'gender' : string,
  'photo' : [] | [ExternalBlob],
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptFriendRequest' : ActorMethod<[UserId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateProfile' : ActorMethod<[Profile], undefined>,
  'declineFriendRequest' : ActorMethod<[UserId], undefined>,
  'findUsersByInterest' : ActorMethod<[string], Array<Profile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<[UserId], Array<Message>>,
  'getFriendCount' : ActorMethod<[UserId], bigint>,
  'getFriendSuggestions' : ActorMethod<[], Array<UserId>>,
  'getFriends' : ActorMethod<[], Array<UserId>>,
  'getPendingFriendRequests' : ActorMethod<[], Array<UserId>>,
  'getProfile' : ActorMethod<[UserId], [] | [Profile]>,
  'getProfilesByAgeRange' : ActorMethod<[bigint, bigint], Array<Profile>>,
  'getProfilesByGender' : ActorMethod<[string], Array<Profile>>,
  'getUserFriends' : ActorMethod<[Principal], Array<UserId>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'removeFriend' : ActorMethod<[UserId], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'searchProfilesByInterests' : ActorMethod<[Array<string>], Array<Profile>>,
  'searchProfilesByLocation' : ActorMethod<[string], Array<Profile>>,
  'sendFriendRequest' : ActorMethod<[UserId], undefined>,
  'sendMessage' : ActorMethod<[UserId, string], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];