/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserId = IDL.Principal;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Profile = IDL.Record({
  'age' : IDL.Nat,
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'interests' : IDL.Vec(IDL.Text),
  'city' : IDL.Text,
  'gender' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'to' : UserId,
  'content' : IDL.Text,
  'from' : UserId,
  'timestamp' : Time,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptFriendRequest' : IDL.Func([UserId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateProfile' : IDL.Func([Profile], [], []),
  'declineFriendRequest' : IDL.Func([UserId], [], []),
  'findUsersByInterest' : IDL.Func([IDL.Text], [IDL.Vec(Profile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func([UserId], [IDL.Vec(Message)], ['query']),
  'getFriendCount' : IDL.Func([UserId], [IDL.Nat], ['query']),
  'getFriendSuggestions' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
  'getFriends' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
  'getPendingFriendRequests' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
  'getProfile' : IDL.Func([UserId], [IDL.Opt(Profile)], ['query']),
  'getProfilesByAgeRange' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Profile)],
      ['query'],
    ),
  'getProfilesByGender' : IDL.Func([IDL.Text], [IDL.Vec(Profile)], ['query']),
  'getUserFriends' : IDL.Func([IDL.Principal], [IDL.Vec(UserId)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'removeFriend' : IDL.Func([UserId], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'searchProfilesByInterests' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(Profile)],
      ['query'],
    ),
  'searchProfilesByLocation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Profile)],
      ['query'],
    ),
  'sendFriendRequest' : IDL.Func([UserId], [], []),
  'sendMessage' : IDL.Func([UserId, IDL.Text], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserId = IDL.Principal;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Profile = IDL.Record({
    'age' : IDL.Nat,
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'interests' : IDL.Vec(IDL.Text),
    'city' : IDL.Text,
    'gender' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
  });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'to' : UserId,
    'content' : IDL.Text,
    'from' : UserId,
    'timestamp' : Time,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptFriendRequest' : IDL.Func([UserId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateProfile' : IDL.Func([Profile], [], []),
    'declineFriendRequest' : IDL.Func([UserId], [], []),
    'findUsersByInterest' : IDL.Func([IDL.Text], [IDL.Vec(Profile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func([UserId], [IDL.Vec(Message)], ['query']),
    'getFriendCount' : IDL.Func([UserId], [IDL.Nat], ['query']),
    'getFriendSuggestions' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
    'getFriends' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
    'getPendingFriendRequests' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
    'getProfile' : IDL.Func([UserId], [IDL.Opt(Profile)], ['query']),
    'getProfilesByAgeRange' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Profile)],
        ['query'],
      ),
    'getProfilesByGender' : IDL.Func([IDL.Text], [IDL.Vec(Profile)], ['query']),
    'getUserFriends' : IDL.Func([IDL.Principal], [IDL.Vec(UserId)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'removeFriend' : IDL.Func([UserId], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'searchProfilesByInterests' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(Profile)],
        ['query'],
      ),
    'searchProfilesByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Profile)],
        ['query'],
      ),
    'sendFriendRequest' : IDL.Func([UserId], [], []),
    'sendMessage' : IDL.Func([UserId, IDL.Text], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };